# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

!if "$(VERBOSE)" != "1"
VV=@
!endif

CC=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\cl.exe
CXX=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\cl.exe
AS=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\ml64.exe
MRC=C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\rc.exe

LD=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\link.exe
AR=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\link.exe
SH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\link.exe

WebGpu_LD=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\link.exe
WebGpu_CXX=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\cl.exe
WebGpu_CXX=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\cl.exe

WebGpu_CXXFLAGS=-nologo -O2 -DGLFW_INCLUDE_NONE /EHsc -external:W0 -external:IC:\Users\jerem\AppData\Local\.xmake\packages\g\glfw\3.4\fc47358da159466996f7d289b4cf1b4e\include -external:W0 -external:IC:\Users\jerem\AppData\Local\.xmake\packages\w\wgpu-native\v0.19.4+1\b179cf2a0b3d4699904289b2d3949c9c\include -external:W0 -external:IC:\Users\jerem\AppData\Local\.xmake\packages\w\wgpu-native\v0.19.4+1\b179cf2a0b3d4699904289b2d3949c9c\include\webgpu -DNDEBUG
WebGpu_CXXFLAGS=-nologo -O2 -DGLFW_INCLUDE_NONE /EHsc -external:W0 -external:IC:\Users\jerem\AppData\Local\.xmake\packages\g\glfw\3.4\fc47358da159466996f7d289b4cf1b4e\include -external:W0 -external:IC:\Users\jerem\AppData\Local\.xmake\packages\w\wgpu-native\v0.19.4+1\b179cf2a0b3d4699904289b2d3949c9c\include -external:W0 -external:IC:\Users\jerem\AppData\Local\.xmake\packages\w\wgpu-native\v0.19.4+1\b179cf2a0b3d4699904289b2d3949c9c\include\webgpu -DNDEBUG
WebGpu_LDFLAGS=-nologo -dynamicbase -nxcompat -machine:x64 -libpath:C:\Users\jerem\AppData\Local\.xmake\packages\g\glfw\3.4\fc47358da159466996f7d289b4cf1b4e\lib -libpath:C:\Users\jerem\AppData\Local\.xmake\packages\w\wgpu-native\v0.19.4+1\b179cf2a0b3d4699904289b2d3949c9c\lib /opt:ref /opt:icf glfw3.lib opengl32.lib wgpu_native.lib user32.lib shell32.lib gdi32.lib Advapi32.lib bcrypt.lib d3dcompiler.lib NtDll.lib User32.lib Userenv.lib WS2_32.lib Gdi32.lib Opengl32.lib

default:  WebGpu

all:  WebGpu

.PHONY: default all  WebGpu

WebGpu: build\windows\x64\release\WebGpu.exe
build\windows\x64\release\WebGpu.exe: build\.objs\WebGpu\windows\x64\release\src\main.cpp.obj
	@echo linking.release WebGpu.exe
	-@mkdir build\windows\x64\release > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\link.exe" $(WebGpu_LDFLAGS) -out:build\windows\x64\release\WebGpu.exe build\.objs\WebGpu\windows\x64\release\src\main.cpp.obj

build\.objs\WebGpu\windows\x64\release\src\main.cpp.obj: src\main.cpp
	@echo compiling.release src\main.cpp
	-@mkdir build\.objs\WebGpu\windows\x64\release\src > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\cl.exe" -c $(WebGpu_CXXFLAGS) -Fobuild\.objs\WebGpu\windows\x64\release\src\main.cpp.obj src\main.cpp

clean:  clean_WebGpu

clean_WebGpu: 
	@del /F /Q build\windows\x64\release\WebGpu.exe > NUL 2>&1 || rmdir /S /Q build\windows\x64\release\WebGpu.exe > NUL 2>&1
	@del /F /Q build\windows\x64\release\WebGpu.pdb > NUL 2>&1 || rmdir /S /Q build\windows\x64\release\WebGpu.pdb > NUL 2>&1
	@del /F /Q build\.objs\WebGpu\windows\x64\release\src\main.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\WebGpu\windows\x64\release\src\main.cpp.obj > NUL 2>&1

